Desktop version
rychrr/portofolio_page pull request #5
Opened 2023-05-06 20:32 UTC by rychrr

Hi, 

I have updated the portfolio  desktop version  and also made adjustment to improve responsiveness of the page

Regards,

2023-05-06 21:05 UTC, zieeco requested changes
Hi @rychrr,

<img height="222" src="https://media0.giphy.com/media/2yLNN4wTy7Zr8JSXHB/giphy-downsized-medium.gif"/>


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._




## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 21:05 UTC, zieeco commented on style.css
### contact section desktop version


- Hey, let's align the content of this section on the desktop version to be close to the Figma design to make our design consistent. see the images below to improve your design:

*Your design*
![image](https://user-images.githubusercontent.com/59397159/236646285-56063b61-a40d-4cdd-a02c-a5ed9b796949.png)


*Figma design*
![image](https://user-images.githubusercontent.com/59397159/236646340-29bd9c4e-0fc2-4004-92f5-5002f4012954.png)

2023-05-06 21:05 UTC, zieeco commented on style.css
>    display: flex;
- Hey, let's also reduce the spaces in between each icon to improve our design as compared with the Figma design:

*Your design*
![image](https://user-images.githubusercontent.com/59397159/236646321-df9d27ae-ea2f-4779-b7e4-e83032c96125.png)

*figma design*
![image](https://user-images.githubusercontent.com/59397159/236646451-54cf1a3f-e7cd-4e00-b4b6-0734288b40c4.png)

2023-05-11 12:08 UTC, rychrr commented on style.css
>    width: 100vw;
Thank you this was resolved

2023-05-11 13:53 UTC, Kossi-stack approved these changes
## Status: Approved ✔️

**Hi @rychrr,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 

![128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c](https://user-images.githubusercontent.com/81444338/150871274-7d1b779c-88e6-420b-a530-b7b905eaa3ac.gif)

You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-05-11 16:20 UTC, merged